name: "🌐 Website Issue Report"
description: Report an issue, an optimization request or an documentation issue specifically related to the website.
labels: "website"

body:
  - type: markdown
    attributes:
      value: |
        **IMPORTANT:** Failure to comply with the following guidelines may result in immediate closure.
        - Prior to submitting, kindly search the closed issues to check if the problem you are reporting has already been addressed and resolved. If you come across a closed issue that pertains to your problem, please leave a comment on that issue instead of creating a new one.
        - If the problem is related to a bug in the website, kindly check for browser compatibility and ensure the issue occurs in multiple browsers before submitting.
        - For suggestions, questions, or feature requests, please use the [Discussions section.](https://github.com/community-scripts/ProxmoxVE/discussions)
  
  - type: input
    id: guidelines
    attributes:
      label: Please verify that you have read and understood the guidelines.
      placeholder: 'yes'
    validations:
      required: true

  - type: dropdown
    id: issue_type
    validations:
      required: true
    attributes:
      label: What type of issue is this?
      options:
        - 
        - Bug
        - Optimization
        - Documentation
        - Other
  
  - type: textarea
    id: bug_description
    attributes:
      label: A clear and concise description of the issue.
    validations:
      required: true

  - type: dropdown
    id: browser
    validations:
      required: true
    attributes:
      label: Which browser are you using?
      options:
        - 
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Other
  
  - type: markdown
    attributes:
      value: |
        **If the issue is browser-related**, please provide information on the version and platform (Windows, MacOS, Linux, etc.).

  - type: textarea
    id: screenshot
    attributes:
      label: If relevant, including screenshots or a code block can be helpful in clarifying the issue.
      placeholder: "Code blocks begin and conclude by enclosing the code with three backticks (```) above and below it."
    validations:
      required: false

  - type: textarea
    id: reproduce
    attributes:
      label: Please provide detailed steps to reproduce the issue.
      placeholder: "First do this, then this ..."
    validations:
      required: false
